- hosts: "tag_Name_{{client_name}}"
  gather_facts: false
  run_once: true
  pre_tasks:
  - name: Load Client configuration
    include_tasks: common/load-configuration.yml
  tasks:
  - name: Create a new Swarm Cluster
    docker_swarm:
       state: "present"
       advertise_addr: "{{lagoon_map.private_ip}}"
       docker_host: "tcp://localhost:2376"
       cert_path: "{{client_params.docker.tlscert}}"
       key_path: "{{client_params.docker.tlskey}}"
       cacert_path: "{{client_params.docker.tlscacert}}"
       tls_verify: True
    register: tokens
  - debug: var=tokens.swarm_facts.JoinTokens.Worker
  - set_fact:
      worker_token: "{{tokens.swarm_facts.JoinTokens.Worker}}"
      manager_token: "{{tokens.swarm_facts.JoinTokens.Manager}}"
      manager_master: "{{lagoon_map.private_ip}}"

- hosts: "tag_Name_{{client_name}}"
  tasks:
  - name: Add nodes
    docker_swarm:
       state: "join"
       advertise_addr: "{{lagoon_map.private_ip}}"
       join_token: "{{hostvars[groups['tag_Name_'+client_name][0]]['worker_token']}}"
       remote_addrs: ["{{hostvars[groups['tag_Name_'+client_name][0]]['manager_master']}}:2377"]
