- name: Include vars of client
  include_vars:
    dir: "{{config_dir}}/input"
    extensions: 
    - yml
    name: client_params
- set_fact:
    proxy_env: "{{client_params.proxy_env}}"
  when: client_params.proxy_env is defined

- name: Load paths
  set_fact:
    client_env:
      provider_path: "{{ lookup('env','PROVIDER_PATH') }}"
- name: Map Provider inventory variables
  include_vars:
    file: "{{client_env.provider_path}}/map-variables.yml"
    name: lagoon_map
