- name: Include vars of client
  include_vars:
    dir: "{{config_dir}}/input/config"
    extensions: 
    - yml
    name: client_params
- set_fact:
    proxy_env: "{{client_params.proxy_env}}"
  when: client_params.proxy_env is defined

- name: Include env vars
  include_vars:
    dir: "{{config_dir}}/input/env"
    extensions: 
    - yml
    name: client_env
  no_log: True

- name: Map Provider inventory variables
  include_vars:
    file: "{{client_env.provider_path}}/map-variables.yml"
    name: lagoon_map
