- set_fact:
    ca_cn: "{{client_params.client.name}}_{{client_params.client.uid}}"
    remote_ca_path: "{{ client_params.docker.tlscacert | dirname }}"
    local_ca_path: "{{client_params.output_folder}}/certs"
    
- name: Create ssl directory
  connection: local
  file: 
    path: "{{item}}"
    state: directory
    mode: 0770
  with_items:
  - "{{local_ca_path}}"

- name: Create CA key
  command: openssl genrsa -out "{{local_ca_path}}/ca-priv-key.pem" 4096
  connection: local
  args:
    creates: "{{local_ca_path}}/ca-priv-key.pem"
    
- name: Create CA
  connection: local
  command: > 
    openssl req -new -x509 -days 3650 
      -key "{{local_ca_path}}/ca-priv-key.pem" 
      -out "{{local_ca_path}}/{{ client_params.docker.tlscacert | basename }}"
      -subj "/CN={{ca_cn}}/C=FR"
  args:
    creates: "{{local_ca_path}}/{{ client_params.docker.tlscacert | basename }}"
    
    
- name: Create ssl directory
  become: yes
  file: 
    path: "{{item}}"
    state: directory
    mode: 0750
    group: docker
  with_items:
  - "{{remote_ca_path}}"

- name: Push CA certificate
  become: yes
  copy:
    src: "{{local_ca_path}}/{{item}}"
    dest: "{{remote_ca_path}}/{{item}}"
  with_items:
  - "{{ client_params.docker.tlscacert | basename }}"
  - "ca-priv-key.pem"
    
- name: Create server key
  become: yes
  command: openssl genrsa -out "{{remote_ca_path}}/{{ client_params.docker.tlskey | basename }}" 4096
  args:
    creates: "{{remote_ca_path}}/{{ client_params.docker.tlskey | basename }}"
- name: Create Server csr
  become: yes
  command: openssl req -subj "/CN={{ca_cn}}" -new -key "{{remote_ca_path}}/{{ client_params.docker.tlskey | basename }}" -out "{{remote_ca_path}}/server.csr"
  args:
    creates: "{{remote_ca_path}}/server.csr"
- name: Create server cnf file
  become: yes
  copy:
    content: |
      extendedKeyUsage = clientAuth,serverAuth
      subjectAltName = DNS:localhost,IP:{{ private_ip }},IP:127.0.0.1,IP:{{ public_ip }}
    dest: "{{remote_ca_path}}/server-extfile.cnf"
    force: no
- name: Create Server certificate
  become: yes
  command: >
    openssl x509 -req -days 3650 
      -in "{{remote_ca_path}}/server.csr"
      -CA "{{remote_ca_path}}/{{ client_params.docker.tlscacert | basename }}"
      -CAkey "{{remote_ca_path}}/ca-priv-key.pem"
      -CAcreateserial 
      -out "{{remote_ca_path}}/{{ client_params.docker.tlscert | basename }}"
      -extfile "{{remote_ca_path}}/server-extfile.cnf"
  args:
    creates: "{{remote_ca_path}}/{{ client_params.docker.tlscert | basename }}"

- name: Find certificates files
  become: yes
  find:
    paths: "{{remote_ca_path}}"
    patterns: "*.*"
  register: files_to_change

- name: Modify the file permissions
  become: yes
  file:
    path: "{{ item.path }}"
    group: docker
    mode: 0640
  with_items: "{{ files_to_change.files }}"
#- name: Create client key
#  become: yes
#  command: openssl genrsa -out "{{remote_ca_path}}/client-priv-key.pem" 4096
#  args:
#    creates: "{{remote_ca_path}}/client-priv-key.pem"
#- name: Create Client csr
#  become: yes
#  command: openssl req -subj "/CN=client" -new -key "{{remote_ca_path}}/client-priv-key.pem" -out "{{remote_ca_path}}/client.csr"
#  args:
#    creates: "{{remote_ca_path}}/client.csr"
#- name: Create client cnf file
#  become: yes
#  copy:
#    content: |
#      extendedKeyUsage = clientAuth,serverAuth
#    dest: "{{remote_ca_path}}/client-extfile.cnf"
#    force: no
#- name: Create Client certificate
#  become: yes
#  command: >
#    openssl x509 -req -days 3650 
#      -in "{{remote_ca_path}}/client.csr"
#      -CA "{{remote_ca_path}}/ca.pem"
#      -CAkey "{{remote_ca_path}}/ca-priv-key.pem"
#      -CAcreateserial 
#      -out "{{remote_ca_path}}/client-cert.pem"
#      -extfile "{{remote_ca_path}}/client-extfile.cnf"
#  args:
#    creates: "{{remote_ca_path}}/client-cert.pem"

- name: Create docker directories
  become: yes
  file: path="{{item}}" state=directory mode=0755
  with_items:
    - /etc/systemd/system/docker.service.d

##### Custom config
- name: Install custom configuration
  become: yes
  copy:
    src: templates/docker.conf
    dest: /etc/systemd/system/docker.service.d

