- name: Add dockremap group
  become: yes
  group: 
    name: dockremap 
    state: present
- name: Create new user to remap root
  become: yes
  user:
    name: dockremap
    comment: "User to remap docker"
    group: dockremap
    shell: /bin/false
- name: Copy configuration for docker remap
  become: yes
  copy:
    src: "{{item}}"
    dest: /etc/
  with_items:
  - templates/namespace/subgid
  - templates/namespace/subuid

