- name : Get Docker's official GPG key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
- name: Add stable repository
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    state: present
- name: Install docker
  become: yes
  apt:
      name={{ item }}
      state=present
      update_cache=yes
  with_items:
  - docker-ce
#  - docker-ce=17.12.1~ce-0~ubuntu
#      - docker-ce=17.03.1~ce-0~ubuntu-xenial
