---
# tasks file for docker
- name: Install docker/ansible configuration
  include_tasks: docker-ansible.yml
  tags: ansible
    
- name: Add docker group
  include_tasks: docker-group.yml
  tags: docker.install
  
- name: Install docker
  include_tasks: install.yml
  tags: docker.install

- name: Add TLS for docker
  include_tasks: config-tls.yml
  when: client_params.docker.tls is defined
  tags: docker.install

- name: Add Proxies for docker
  include_tasks: proxies.yml
  when: client_params.proxy is defined
  tags: docker.install

- name: Add Usernamespace for docker
  include_tasks: config-user-ns.yml
  when: client_params.docker['userns-remap'] is defined
  tags: docker.install

- name: Update configuration
  include_tasks: update-json.yml docker_daemon_new_config="{{client_params.docker}}" 

- name: Start docker
  include_tasks: daemon-start.yml
  tags: 
  - docker.install
  - docker.config
